services:
  my-porto-backend:
    container_name: my-porto-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ninisrv-mysql
      DB_PORT: "3306"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run db:migrate && npm run dev"
    networks:
      - default
      - web
    restart: unless-stopped

networks:
  web:
    external: true
