services:
  my-porto-backend:
    container_name: my-porto-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_DIALECT: ${DB_DIALECT:-mysql}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run db:migrate && npm run dev"
    networks:
      - default
      - web
    restart: unless-stopped

networks:
  web:
    external: true
